update credits

diff --git a/packages/system/box b/packages/system/box
--- a/packages/system/box
+++ b/packages/system/box
@@ -43,60 +43,60 @@ _tan=$(tput setaf 3)
 _cyan=$(tput setaf 6)
 
 function _excute() {
-    ($1 >> "${OUTTO}" 2>&1;)
+	($1 >>"${OUTTO}" 2>&1)
 }
 function _print() {
-    printf "${_norm}%s${_norm}\n" "$@"
+	printf "${_norm}%s${_norm}\n" "$@"
 }
 function _info() {
-    printf "${_cyan}➜ %s${_norm}\n" "$@"
+	printf "${_cyan}➜ %s${_norm}\n" "$@"
 }
 function _success() {
-    printf "${_green}✓ %s${_norm}\n" "$@"
+	printf "${_green}✓ %s${_norm}\n" "$@"
 }
 function _warning() {
-    printf "${_tan}⚠ %s${_norm}\n" "$@"
+	printf "${_tan}⚠ %s${_norm}\n" "$@"
 }
 function _error() {
-    printf "${_red}✗ %s${_norm}\n" "$@"
+	printf "${_red}✗ %s${_norm}\n" "$@"
 }
 #################################################################################
 # SCRIPT FUNCTIONS
 #################################################################################
 function _batchInstall() {
-    applist=()
-    locks=($(find /usr/local/bin/quickbox/package/install -type f -printf "%f\n" | cut -d "-" -f 2 | grep -v "Template\|lecert\|denyhosts\|fail2ban" | sort -d))
-    for i in "${locks[@]}"; do
-        app=${i}
-        if [[ ! -f /install/.$app.lock && ! -f /install/.*.$app.lock ]]; then
-            applist+=("$i" '""')
-        fi
-    done
-    installlist=$(whiptail --title "Install Software" --checklist --noitem --separate-output "Make some choices:" 20 28 14 "${applist[@]}" 3>&1 1>&2 2>&3)
-    echo "Batch Installing..."
-    for i in ${installlist[@]}; do
-        source /usr/local/bin/quickbox/package/install/installpackage-$i
-    done
+	applist=()
+	locks=($(find /usr/local/bin/quickbox/package/install -type f -printf "%f\n" | cut -d "-" -f 2 | grep -v "Template\|lecert\|denyhosts\|fail2ban" | sort -d))
+	for i in "${locks[@]}"; do
+		app=${i}
+		if [[ ! -f /install/.$app.lock && ! -f /install/.*.$app.lock ]]; then
+			applist+=("$i" '""')
+		fi
+	done
+	installlist=$(whiptail --title "Install Software" --checklist --noitem --separate-output "Make some choices:" 20 28 14 "${applist[@]}" 3>&1 1>&2 2>&3)
+	echo "Batch Installing..."
+	for i in ${installlist[@]}; do
+		source /usr/local/bin/quickbox/package/install/installpackage-$i
+	done
 }
 
 function _help() {
-    # print help info
-    echo -e "\nQuickBox Lite Cli Tools"
-    echo -e "\nUsage: \n$(basename "$0") COMMAND"
-    echo -e "\nOptions:\n"
-    echo "install <appname>                 install applications, leave appname"
-    echo "                                  blank to use batch install"
-    echo "remove <appname>                  remove installed application"
-    echo "update <appname>                  upgrade installed application"
-    echo "lang <de|dk|en|es|fr|zh>          change dashboard language"
-    echo "clean <mem|log>                   clean memory or installation log"
-    echo "fix <dpkg|time|interface|home>    fix your setting"    
-    echo "set <interface|passwd|mount>      change interface setting/password"
-    echo "iotest                            run IO test"
-    echo "troubleshoot                      generate log for troubleshoot"
-    echo "unban <IP adress>                 remove a IP/all IP from banned list"
-    echo ""
-    echo "help                              display this help and exit"
+	# print help info
+	echo -e "\nQuickBox Lite Cli Tools"
+	echo -e "\nUsage: \n$(basename "$0") COMMAND"
+	echo -e "\nOptions:\n"
+	echo "install <appname>                 install applications, leave appname"
+	echo "                                  blank to use batch install"
+	echo "remove <appname>                  remove installed application"
+	echo "update <appname>                  upgrade installed application"
+	echo "lang <de|dk|en|es|fr|zh>          change dashboard language"
+	echo "clean <mem|log>                   clean memory or installation log"
+	echo "fix <dpkg|interface|home>         fix your setting"
+	echo "set <interface|passwd|mount>      change interface setting/password"
+	echo "iotest                            run IO test"
+	echo "troubleshoot                      generate log for troubleshoot"
+	echo "unban <IP adress>                 remove a IP/all IP from banned list"
+	echo ""
+	echo "help                              display this help and exit"
 }
 #################################################################################
 # ARGUMENT SETTING
@@ -104,121 +104,120 @@ function _help() {
 resolver=$1
 
 if [[ $resolver == "lang" ]]; then
-    langname=$2
-    case $langname in
-        "de"|"deutsch"|"germany"|"lang_de") bash /usr/local/bin/quickbox/system/lang/langSelect-lang_de;;
-        "dk"|"dansk"|"danish"|"lang_dk") bash /usr/local/bin/quickbox/system/lang/langSelect-lang_dk;;
-        "en"|"en-us"|"english"|"lang_en") bash /usr/local/bin/quickbox/system/lang/langSelect-lang_en;;
-        "es"|"spanish"|"lang_es") bash /usr/local/bin/quickbox/system/lang/langSelect-lang_es;;
-        "fr"|"french"|"lang_fr") bash /usr/local/bin/quickbox/system/lang/langSelect-lang_fr;;
-        "zh"|"zh-cn"|"chinese"|"lang_zh-cn"|"lang_zh") bash /usr/local/bin/quickbox/system/lang/langSelect-lang_zh-cn;;
-    esac
+	langname=$2
+	case $langname in
+	"de" | "deutsch" | "germany" | "lang_de") bash /usr/local/bin/quickbox/system/lang/langSelect-lang_de ;;
+	"dk" | "dansk" | "danish" | "lang_dk") bash /usr/local/bin/quickbox/system/lang/langSelect-lang_dk ;;
+	"en" | "en-us" | "english" | "lang_en") bash /usr/local/bin/quickbox/system/lang/langSelect-lang_en ;;
+	"es" | "spanish" | "lang_es") bash /usr/local/bin/quickbox/system/lang/langSelect-lang_es ;;
+	"fr" | "french" | "lang_fr") bash /usr/local/bin/quickbox/system/lang/langSelect-lang_fr ;;
+	"zh" | "zh-cn" | "chinese" | "lang_zh-cn" | "lang_zh") bash /usr/local/bin/quickbox/system/lang/langSelect-lang_zh-cn ;;
+	esac
 fi
 
 if [[ $resolver == "install" ]]; then
-    extraarg="${@:2}"
-    appname=$2
-    if [[ -z $extraarg ]]; then
-        _batchInstall
-    elif [[ $appname == "bbr" || $appname == "BBR" ]]; then
-        bash /usr/local/bin/quickbox/system/auxiliary/install-BBR.sh ${@:3}
-    else
-        if [[ -f /usr/local/bin/quickbox/package/install/installpackage-${appname} ]]; then
-            bash /usr/local/bin/quickbox/package/install/installpackage-${appname} ${@:3}
-        else
-            _error "${appname} Installer not exist"
-        fi
-    fi
+	extraarg="${@:2}"
+	appname=$2
+	if [[ -z $extraarg ]]; then
+		_batchInstall
+	elif [[ $appname == "bbr" || $appname == "BBR" ]]; then
+		bash /usr/local/bin/quickbox/system/auxiliary/install-BBR.sh ${@:3}
+	else
+		if [[ -f /usr/local/bin/quickbox/package/install/installpackage-${appname} ]]; then
+			bash /usr/local/bin/quickbox/package/install/installpackage-${appname} ${@:3}
+		else
+			_error "${appname} Installer not exist"
+		fi
+	fi
 fi
 
 if [[ $resolver == "remove" ]]; then
-    extraarg="${@:2}"
-    appname=$2
-    if [[ -z $extraarg ]]; then
-         _error "Nothing will be removed"
-    else
-        if [[ -f /usr/local/bin/quickbox/package/remove/removepackage-${appname} ]]; then
-            bash /usr/local/bin/quickbox/package/remove/removepackage-${appname} ${@:3}
-        else
-            _error "Nothing will be removed"
-        fi
-    fi
+	extraarg="${@:2}"
+	appname=$2
+	if [[ -z $extraarg ]]; then
+		_error "Nothing will be removed"
+	else
+		if [[ -f /usr/local/bin/quickbox/package/remove/removepackage-${appname} ]]; then
+			bash /usr/local/bin/quickbox/package/remove/removepackage-${appname} ${@:3}
+		else
+			_error "Nothing will be removed"
+		fi
+	fi
 fi
 
 if [[ $resolver == "update" ]]; then
-    extraarg="${@:2}"
-    appname=$2
-    if [[ $appname == "quickbox" ]]; then
-        bash /usr/local/bin/quickbox/system/qbUpdate
-    elif [[ ! -z $extraarg ]]; then
-        if [[ -f /usr/local/bin/quickbox/package/update/updatepackage-${appname} ]]; then
-            bash /usr/local/bin/quickbox/package/update/updatepackage-${appname} ${@:3}
-        else
-            _error "Updater not exist"
-        fi
-    fi
+	extraarg="${@:2}"
+	appname=$2
+	if [[ $appname == "quickbox" ]]; then
+		bash /usr/local/bin/quickbox/system/qbUpdate
+	elif [[ ! -z $extraarg ]]; then
+		if [[ -f /usr/local/bin/quickbox/package/update/updatepackage-${appname} ]]; then
+			bash /usr/local/bin/quickbox/package/update/updatepackage-${appname} ${@:3}
+		else
+			_error "Updater not exist"
+		fi
+	fi
 fi
 
 if [[ $resolver == "clean" ]]; then
-    command=$2
-    if [[ $command == "mem" || $command == "memory" ]]; then
-        bash /usr/local/bin/quickbox/system/auxiliary/clean_mem
-    elif [[ $command == "log" ]]; then
-        bash /usr/local/bin/quickbox/system/auxiliary/clean_log
-    fi
+	command=$2
+	if [[ $command == "mem" || $command == "memory" ]]; then
+		bash /usr/local/bin/quickbox/system/auxiliary/clean_mem
+	elif [[ $command == "log" ]]; then
+		bash /usr/local/bin/quickbox/system/auxiliary/clean_log
+	fi
 fi
 
 if [[ $resolver == "troubleshoot" ]]; then
-    bash /usr/local/bin/quickbox/system/auxiliary/logCollector.sh
+	bash /usr/local/bin/quickbox/system/auxiliary/logCollector.sh
 fi
 
 if [[ $resolver == "set" ]]; then
-    command=$2
-    case $command in
-        "interface")
-            echo $3 > /srv/dashboard/db/interface.txt
-            \cp -f /etc/QuickBox/setup/dashboard/widgets/stat.php /srv/dashboard/widgets/stat.php
-            \cp -f /etc/QuickBox/setup/dashboard/widgets/data.php /srv/dashboard/widgets/data.php
-            \cp -f /etc/QuickBox/setup/dashboard/widgets/bw_tables.php /srv/dashboard/widgets/bw_tables.php
-            \cp -f /etc/QuickBox/setup/dashboard/inc/config.php /srv/dashboard/inc/config.php
-            bash /usr/local/bin/quickbox/system/auxiliary/set_interface
-            chown -R www-data: /srv/dashboard
-            ;;
-        "passwd"|"password")
-            bash /usr/local/bin/quickbox/system/users/changePass -p ${@:3}
-            ;;
-        "mount")
-            bash /usr/local/bin/quickbox/system/auxiliary/set_mount ${@:3}
-            ;;
-    esac
+	command=$2
+	case $command in
+	"interface")
+		echo $3 >/srv/dashboard/db/interface.txt
+		\cp -f /etc/QuickBox/setup/dashboard/widgets/stat.php /srv/dashboard/widgets/stat.php
+		\cp -f /etc/QuickBox/setup/dashboard/widgets/data.php /srv/dashboard/widgets/data.php
+		\cp -f /etc/QuickBox/setup/dashboard/widgets/bw_tables.php /srv/dashboard/widgets/bw_tables.php
+		\cp -f /etc/QuickBox/setup/dashboard/inc/config.php /srv/dashboard/inc/config.php
+		bash /usr/local/bin/quickbox/system/auxiliary/set_interface
+		chown -R www-data: /srv/dashboard
+		;;
+	"passwd" | "password")
+		bash /usr/local/bin/quickbox/system/users/changePass -p ${@:3}
+		;;
+	"mount")
+		bash /usr/local/bin/quickbox/system/auxiliary/set_mount ${@:3}
+		;;
+	esac
 fi
 
 if [[ $resolver == "fix" ]]; then
-    command=$2
-    case $command in
-        "dpkg"|"lock") bash /usr/local/bin/quickbox/system/auxiliary/fixDpkg;;
-        "time") bash /usr/local/bin/quickbox/system/auxiliary/fixTime;;
-        "interface") bash /usr/local/bin/quickbox/system/auxiliary/set_interface;;
-        "home") bash /usr/local/bin/quickbox/system/auxiliary/fixHome ${@:3};;
-    esac
+	command=$2
+	case $command in
+	"dpkg" | "lock") bash /usr/local/bin/quickbox/system/auxiliary/fixDpkg ;;
+	"interface") bash /usr/local/bin/quickbox/system/auxiliary/set_interface ;;
+	"home") bash /usr/local/bin/quickbox/system/auxiliary/fixHome ${@:3} ;;
+	esac
 fi
 
 if [[ $resolver =~ ("iotest"|"disktest") ]]; then
-    bash /usr/local/bin/quickbox/system/auxiliary/iotest ${@:2}
+	bash /usr/local/bin/quickbox/system/auxiliary/iotest ${@:2}
 fi
 
 if [[ $resolver == "unban" ]]; then
-    if [[ -f /install/.denyhosts.lock ]]; then
-        bash /usr/local/bin/quickbox/system/auxiliary/denyunban ${@:2}
-    fi
-    if [[ -f /install/.fail2ban.lock ]]; then
-        bash /usr/local/bin/quickbox/system/auxiliary/failunban ${@:2}
-    fi
+	if [[ -f /install/.denyhosts.lock ]]; then
+		bash /usr/local/bin/quickbox/system/auxiliary/denyunban ${@:2}
+	fi
+	if [[ -f /install/.fail2ban.lock ]]; then
+		bash /usr/local/bin/quickbox/system/auxiliary/failunban ${@:2}
+	fi
 fi
 
 if [[ $resolver == "help" ]]; then
-    _help
-    exit 0
+	_help
+	exit 0
 fi
 
 #################################################################################
@@ -226,7 +225,7 @@ fi
 #################################################################################
 
 if [[ ! $resolver =~ ("lang"|"install"|"remove"|"update"|"clean"|"troubleshoot"|"set"|"fix"|"iotest"|"disktest"|"unban"|"help") ]]; then
-    _error "Command not exist!"
-    _help
-    exit 1
+	_error "Command not exist!"
+	_help
+	exit 1
 fi
